# Generated by Django 5.0.1 on 2026-05-29 03:17

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_unsigned', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='full_name', max_length=255)),
                ('name_unsigned', models.CharField(blank=True, db_column='name_unsigned', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('email_confirmation_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('user_total_success_bookings', models.BigIntegerField(default=0)),
                ('user_total_failed_bookings', models.BigIntegerField(default=0)),
                ('sale_total_bookings', models.BigIntegerField(default=0)),
                ('sale_success_percent', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='models.permission')),
            ],
            options={
                'db_table': 'permissions_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_unsigned', models.CharField(blank=True, max_length=366, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('overal_rating', models.FloatField(default=0.0)),
                ('landing_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, null=True, size=None)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='models.category')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='models.booking')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='models.product')),
            ],
            options={
                'db_table': 'booking_products',
                'managed': True,
                'unique_together': {('booking', 'product')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(related_name='bookings', through='models.BookingProduct', to='models.product'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.ManyToManyField(related_name='roles', through='models.PermissionRole', to='models.permission')),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='permissionrole',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='models.role'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.CharField(default='system', max_length=255)),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='models.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='models.user')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='sale_user',
            field=models.ForeignKey(blank=True, db_column='sale_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_bookings', to='models.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='models.user'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='models.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
            options={
                'db_table': 'users_roles',
                'managed': True,
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='models.UserRole', to='models.role'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, help_text='VNPay order ID (vnp_TxnRef)', max_length=255, unique=True)),
                ('amount', models.BigIntegerField(help_text='Payment amount in VND')),
                ('order_info', models.TextField(blank=True, help_text='Order description (vnp_OrderInfo)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_no', models.CharField(blank=True, db_index=True, help_text='VNPay transaction number (vnp_TransactionNo)', max_length=255, null=True)),
                ('bank_code', models.CharField(blank=True, help_text='Bank code used for payment (vnp_BankCode)', max_length=50, null=True)),
                ('pay_date', models.CharField(blank=True, help_text='Payment date from VNPay (yyyyMMddHHmmss) (vnp_PayDate)', max_length=14, null=True)),
                ('response_code', models.CharField(blank=True, help_text='VNPay response code (vnp_ResponseCode)', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='system', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='models.booking')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='payment_tra_order_i_54c79b_idx'), models.Index(fields=['transaction_no'], name='payment_tra_transac_bfff03_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['-created_at'], name='payment_tra_created_94cd0f_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='permissionrole',
            unique_together={('role', 'permission')},
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=255, unique=True)),
                ('expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='models.user')),
            ],
            options={
                'db_table': 'tokens',
                'managed': True,
                'indexes': [models.Index(fields=['refresh_token'], name='idx_token_refresh_token'), models.Index(fields=['user'], name='idx_token_user_id')],
            },
        ),
    ]
