# Generated by Django 5.0.1 on 2026-05-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
