# Generated by Django 5.0.1 on 2026-05-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_booking_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_account_holder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
